# Project Information
site_name: Seekluna
site_url: https://beyoursven.github.io/seekluna_docs/
site_author: Seekluna

# Repository
repo_name: seekluna_docs
repo_url: https://github.com/beyoursven/seekluna_docs
# edit_uri: edit/main/docs

# Copyright
copyright: 'Copyright &copy; 2019 - 2024 Seekluna Team'

# Contents
nav:
  - CSPJ:
    - 前缀和与差分:
      - 一维前缀和: CSPJ/前缀和与差分/1D_prefix_sum.md
      - 二维前缀和: CSPJ/前缀和与差分/2D_prefix_sum.md
      - 差分: CSPJ/前缀和与差分/diff.md
      - 例题和应用: CSPJ/前缀和与差分/application.md
    - 贪心: 
      - 介绍: CSPJ/贪心/intro.md
      - 题目: CSPJ/贪心/problem.md
    - 数据结构:
      - vector: CSPJ/数据结构/vector.md
      - 栈: CSPJ/数据结构/stack.md
      - 队列: CSPJ/数据结构/queue.md
      - map: CSPJ/数据结构/map.md
      - 链表: CSPJ/数据结构/链表/list.md
      - 题目: CSPJ/数据结构/problem.md
    - 搜索:
      - 搜索和dfs介绍: CSPJ/搜索/dfs_intro.md
      - dfs的四个基本模型: CSPJ/搜索/dfs的四个基本模型.md
      - 另类的搜索: CSPJ/搜索/另类的搜索.md
      - 搜索剪枝: CSPJ/搜索/剪枝.md
      - 状态图遍历: CSPJ/搜索/状态图遍历.md
      - 题单: CSPJ/搜索/problem.md
    - 高精度: CSPJ/高精度/big_int.md
    - 二分:
      - 二分查找: CSPJ/二分/二分查找.md
      - 二分答案: CSPJ/二分/二分答案.md
      - 题单: CSPJ/二分/problem.md
    - 数学:
      - 数学符号: CSPJ/数学/notation.md
      - 数论（约数，质数，公约数）: 
        - 知识点: CSPJ/数学/number_theory.md
        - 习题: CSPJ/数学/number_theory_problem.md
      - 取整: CSPJ/数学/取整.md
      - 同余: CSPJ/数学/同余.md
      - 进制: CSPJ/数学/进制.md
      - 位运算: CSPJ/数学/位运算.md
      - 幂运算: CSPJ/数学/幂运算.md
      - 集合论: CSPJ/数学/集合论.md
      - 组合数学: CSPJ/数学/组合数学.md
      - 题目汇总: CSPJ/数学/problem.md
  - CSPS: 
    - 简介: CSPS/index.md
    - ST 表: CSPS/sparse_table/sparse_table.md
    - 树状数组:   CSPS/fenwick/fenwick.md
    - 区间 DP: CSPS/range_dp/range_dp.md
    - 树 DP: CSPS/tree_dp/tree_dp.md
    - 状压 DP: CSPS/bitmask_dp/bitmask_dp.md
    - 拓扑排序: CSPS/topo/topo.md
    - 数据结构:
      - 二叉堆: 
        - 概念: CSPS/ds/heap/二叉堆.md
        - 应用: CSPS/ds/heap/应用.md
        - 其他: CSPS/ds/heap/其他.md
      - 并查集: ds/dsu/dsu.md
    - STL:
      - 容器:
        - 优先队列: CSPS/STL/容器/pq.md
        - set: CSPS/STL/容器/set.md
        - multiset: CSPS/STL/容器/multiset.md
        - map: CSPS/STL/容器/map.md
        - 参考资料: CSPS/STL/容器/reference.md
  - L2-入门:
    - 输入技巧: L2/io_technique.md
    - string: L2/string.md
    - 双指针: L2/two_pointer.md
    - 贪心:
      - 初步介绍: L2/greedy/intro.md
  - 图论:
    - 最小生成树: graph/mst.md
  - data structure:
    - 栈: ds/stack.md
    - 队列: ds/queue.md
    - c++ stl 容器: ds/stl_container.md
  - 动态规划:
    - 理论: dp/theory/theory.md
    - dp 简介: dp/dp_intro.md
    - 最长上升子序列: dp/LIS.md
    - 背包 dp: dp/knapsack_dp.md
    - 记忆化: dp/memorization.md
    - 单序列 dp: dp/sequence_dp.md
    - 多序列 dp: dp/multi_sequence_dp.md
    - 矩阵 dp: dp/matrix_dp.md


# Theme
theme:
  name: material
  # custom_dir: 'mkdocs-material/material/templates'
  static_templates:
    - 404.html
  language: 'zh'
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  include_search_page: false
  search_index_only: true
  # favicon: 'favicon.ico'
  icon:
    logo: 'material/school'
    repo: fontawesome/brands/github
  features:
    - content.action.edit
    - navigation.tabs
    - navigation.instant
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.bootcdn.net/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js

#extra_javascript:
#  - javascripts/katex.js
#  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
#  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

#extra_css:
#  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

# Extensions
markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: ""
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true